---
# tasks file for role_db
- name: Install MariaDB and dependencies
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: yes
  become: yes
  tags:
    - install

- name: Start and enable MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  become: yes
  tags:
    - config

- name: Wait for MariaDB to start and listen on port 3306
  ansible.builtin.wait_for:
    port: 3306
    host: '127.0.0.1'
    delay: 5
    timeout: 60
  become: no
  tags:
    - config

# --- БЛОК ИДЕМПОТЕНТНОЙ НАСТРОЙКИ ROOT ---
- name: Check if root password is already set (by checking for .my.cnf)
  ansible.builtin.stat:
    path: /root/.my.cnf
  register: root_my_cnf_exists
  become: yes
  tags:
    - config

- name: Set root password and create credentials file
  block:
    - name: Set the root user password for the first time
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create .my.cnf file for root to allow subsequent connections
      ansible.builtin.template:
        src: root.my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'
  when: not root_my_cnf_exists.stat.exists
  become: yes
  tags:
    - config
# --- КОНЕЦ БЛОКА НАСТРОЙКИ ROOT ---

- name: Create the application database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
  become: yes
  tags:
    - config

- name: Create the application database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
  become: yes
  tags:
    - config
