---
# tasks file for role_web
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes # Выполнить с правами sudo
  tags:
    - install

- name: Create Nginx config from template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/myapp
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart Nginx
  tags:
    - config # Это конфигурация

- name: Enable new site configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/myapp
    dest: /etc/nginx/sites-enabled/myapp
    state: link
    force: yes
  become: yes
  notify: Restart Nginx
  tags:
    - config # Это конфигурация

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  notify: Restart Nginx
  tags:
    - config # Это конфигурация

- name: Ensure Nginx is started and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes
  tags:
    - config # Это конфигурация
